openapi: '3.2.0'

servers:
  - url: https://127.0.0.1:8888

info:
# If styling on orange, use gallaghersec-black.png
# url: https://gallaghersecurity.github.io/cc-rest-docs/ref/images/gallagher-black.png
  url: https://gallaghersecurity.github.io/cc-rest-docs/ref/images/gallagher.png
  title: "Command Centre Controller 7000 REST API"
  version: "0.1"

  description: |

    ...

    ## Access control

    Clients authenticate by including a pre-shared API key in the `Authorization` header of each
    request.  Command Centre generates a random API key when you create an endpoint for your clients
    to connect to.  Search the Configuration Client online help for 'REST API' for how do do that.

    In current versions of Command Centre, the API key will be in the format
    `XXXX-XXXX-XXXX-XXXX-XXXX-XXXX-XXXX-XXXX` with each `X` an uppercase hexadecimal digit.
    Future versions of Command Centre may use other formats of API key, so treat it as an opaque
    string.  Tempting as it may be, do not interpret is as a GUID.

    There are two ways you can pass the API key to the server:  following an authorisation method
    of `GGL-API-KEY`, or (in 9.0 and later) in the style of HTTP Basic authentication:  prefixed
    with a colon, Base64-encoded, and following an authorisation method of `Basic`.

    Examples:

    `Authorization: GGL-API-KEY C774-B01F-D695-AA4B-215F-A158-AC22-ADEB`

    `Authorization: Basic OkM3NzQtQjAxRi1ENjk1LUFBNEItMjE1Ri1BMTU4LUFDMjItQURFQg==`

    Do not omit the 'GGL-API-KEY' from the first form.

    #### HTTP Basic authentication

    The two example headers above are equivalent:  prepending a colon to the example API key
    beginning with `C774` then encoding it into Base64 produces the 56 characters beginning with
    `OkM3`.

    According to the HTTP Basic specification, the colon is a separator between a username and a
    password.  In our case, the API key is the password and the username is unnecessary.  If you
    place a username before the colon, before Base64-encoding it, Command Centre will ignore it
    and authenticate the connection based on the API key alone.

    #### Pinning a client TLS certificate

    The REST API also requires a client certificate with each request.  See the Configuration Client
    help for instructions on where to enter REST Client thumbprints.

    #### Symptoms of authentication failures

    ***I have no idea*** what the controller does here.  401s on bad API keys and TLS certificates,
    probably.

    ## Text encoding

    Command Centre's REST API encodes all payloads using UTF-8, and expects clients to do the
    same.  It does not escape special characters in response bodies except where required to embed
    them in JSON.

    Specifically, it does not sanitise HTML, XML, or SQL.  Your clients should expect to receive
    strings exactly as they were sent, even if they were sent by a hostile client.  Write your
    clients to resist injection attacks.

    ### Dates and times

    When you send dates and times to Command Centre you must use an ISO-8601 calendar date, time,
    and time zone designator, with hyphens separating the date fields and colons separating the time
    fields.  This looks like `YYYY-MM-DDTHH:MM:SSZ`, where `T` is an actual T, and `Z` is a timezone
    designator such as 'Z' for UTC or '-0800' for Pacific Standard Time.  Specify up to seven
    decimals on the seconds if you wish, but be aware that some Command Centre fields will not use
    them.  You must supply the year and month but omit the other fields as you like.  Command Centre
    will assume sensible defaults, such as the top of the minute when you omit seconds, midnight
    when you omit the time, or first of the month when you omit the day.

    Do not omit the timezone designator.

security:
  - API_key: []
  - basic: []

components:
  securitySchemes:
    API_key:
      type: apiKey
      name: Authorization
      in: header
      description: |

        Clients authenticate by including a pre-shared API key in the `Authorization` header of each
        request after an authorisation method of `GGL-API-KEY`:

        `Authorization: GGL-API-KEY C774-B01F-D695-AA4B-215F-A158-AC22-ADEB`

        For a fuller description see [Access control](#topic-Access-control).

    basic:
      type: http
      scheme: basic
      description: |
        This is HTTP Basic authentication using a blank username and the API key as the password.

        Example:  `Authorization: Basic OkM3NzQtQjAxRi1ENjk1LUFBNEItMjE1Ri1BMTU4LUFDMjItQURFQg==`

        That example is equivalent to the example in the description of the api_Key method:
        prepending a colon to the API key beginning with `C774` then encoding it into Base64
        produces the 56 characters beginning with `OkM3`.

        The colon is a separator between a username, which is blank in our case, and the password,
        which is our API key.

        For a fuller description see [Access control](#topic-Access-control).

  schemas:
    CredentialType1:
      title: Card-type credential
      description: |
        Send this.  Contains card data.

        TODO Change it to oneOf three different kinds, for integer, string, and hex.  Use shared
        blocks where possible.  Problem:  discriminators arrived in OAS 3.2 but no renderers fully
        support it yet so this syntax might be the best we have for now.
      type: object
      required: [ credentialType, cardNumberFormat, cardNumber, facilityCode ]
      properties:
        credentialType:
          description: |
            This is a lot like our internal badge type, but is not exactly a badge type.

            It has only one acceptable value:  `card`.  Which kind of makes me want to make it
            optional, defaulting to `card`, but we'll see if OpenAPI Spec supports that.

            More badge types to be added in future.
          type: string
          enum: [card]
        cardNumberFormat:
          description: |
            Description of the card number format.  TODO.
          type: string
          enum: [decimal, string, hex]
        cardNumber:
          oneOf:
            - type: string
              description: |
                TODO UTF-8 string.  `cardNumberFormat` MUST be `string`.

                But what if it contains a decimal integer and `cardNumberFormat` is `decimal`?
                Surely that is acceptable too.
            - type: string
              description: TODO hex.  `cardNumberFormat` MUST be `hex`.
              # leading space required for OpenAPI-Explorer.  Not good.
              pattern: " ^([0-9A-F][0-9A-F])+$"
            - type: integer
              minimum: 1
              description: TODO int.  `cardNumberFormat` MUST be `decimal`.
        facilityCode:
          type: integer
          minimum: 1
          maximum: 1048575
          description:
            TODO description of facility codes.  Cover A-P conversion.
        issueLevel:
          type: integer
          minimum: 1
          maximum: 15
          default: 1
          description: |
              ***WHAT IS THE MAXIMUM?***
  
tags:
- name: "Controller API"

paths:
  /api/whatever:
    post:
      tags: [ "Controller API" ]
      summary: Submit a credential to a door
      description: |
        TODO path description
      requestBody:
        description: TODO description of request body
        required: true
        content:
          application/json:
            schema: {$ref: '#/components/schemas/CredentialType1'}
            examples:
              Plain card:
                summary: A card with decimal number and FC.
                value:
                  credentialType: card
                  cardNumberFormat: decimal
                  cardNumber: 23456
                  facilityCode: 8000
              Licence plate:
                summary: A vehicle licence plate.
                value:
                  credentialType: card
                  cardNumberFormat: string
                  cardNumber: "ABC123"
                  facilityCode: 8000
              
      responses:
        "200":
          description: |
            Success.
        "401":
          description: |
            Failure.  Request was not authenticated.
        "403":
          description: |
            Failure.  Authorisation problem.  TODO.
